import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  image: {
    flex: 1,
  },
  top: {
    backgroundColor: "#003279",
    borderBottomLeftRadius: 40,
    borderBottomRightRadius: 40,
    zIndex: 1,
    height: 72,
  },
  info: {
    justifyContent: "space-between",
    flexDirection: "row",
    alignItems: "center",
    marginLeft: 10,
    marginRight: 10,
  },
  date: {
    color: "#FFFFFF",
    fontSize: 16,
  },
  mainTeams: {
    justifyContent: "center",
    flexDirection: "row",
    alignItems: "center",
    marginTop: -12,
  },
  result: {
    fontSize: 28,
    color: "#FFFFFF",
    fontWeight: "bold",
    width: 48,
    textAlign: "center",
    marginLeft: 10,
    marginRight: 10,
  },
  bottom: {
    height: 66,
    backgroundColor: "#FFFFFF",
    marginTop: -40,
    justifyContent: "flex-end",
    alignItems: "center",
    borderBottomLeftRadius: 40,
    borderBottomRightRadius: 40,
  },
  teams: {
    color: "#003279",
    fontSize: 20,
    fontWeight: "bold",
  },
  button: {
    justifyContent: "center",
    alignItems: "center",
  },
  viewButton: {
    width: 120,
    height: 40,
    backgroundColor: "#003279",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 16,
  },
  textButton: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "bold",
  },
  bottomSheet: {
    flex: 1,
    alignItems: "center",
    marginTop: 24,
  },
  contentContainer: {
    flex: 1,
    alignItems: "center",
    height: "auto",
    flexWrap: "wrap",
    flexDirection: "row",
    justifyContent: "center",
    padding: 4,
  },
  typeResult: {
    width: "20%",
    backgroundColor: "#003279",
    height: "16%",
    borderRadius: 30,
    justifyContent: "center",
    alignItems: "center",
    margin: 4,
  },
  resultText: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "bold",
  },
  buttonBack: {
    justifyContent: "center",
    alignItems: "center",
    position: "absolute",
    bottom: 100,
    width: "100%",
  },
  back: {
    backgroundColor: "#003279",
    height: 42,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 16,
  },
  textBack: {
    fontSize: 16,
    color: "#FFFFFF",
    padding: 8,
  },
  viewModal: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0,0,0,0.6)",
  },
  modal: {
    backgroundColor: "#1e293b",
    width: "85%",
    borderRadius: 20,
    padding: 24,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#334155",
  },
  viewModal2: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 25,
  },
  textModal: {
    color: "#94a3b8",
    marginBottom: 8,
    fontSize: 12,
  },
  textinput: {
    backgroundColor: "#0f172a",
    color: "#fff",
    width: 60,
    height: 50,
    borderRadius: 10,
    textAlign: "center",
    fontSize: 20,
    fontWeight: "bold",
  },
  button: {
    backgroundColor: "#22c55e",
    width: "100%",
    paddingVertical: 14,
    borderRadius: 10,
    alignItems: "center",
    marginBottom: 12,
  },
  textCalc: {
    color: "#fff",
    fontWeight: "bold",
    fontSize: 16,
  },
  buttonClose: {
    width: "100%",
    paddingVertical: 10,
    alignItems: "center",
  },
  textClose: {
    color: "#94a3b8",
    fontSize: 14,
  },
  adminButton: {
    backgroundColor: "#e11d48",
    paddingVertical: 16,
    marginHorizontal: 20,
    borderRadius: 12,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    bottom: -250,
  },
  viewBlock: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 20,
  },
  textBlock: {
    color: "#fff",
    fontSize: 14,
    textAlign: "center",
    fontWeight: "500",
  },
});

export default styles;
