export const TeamList = [
  { value: "Albania", code: "al" },
  { value: "Anglia", code: "GB-ENG" },
  { value: "Austria", code: "at" },
  { value: "Belgia", code: "be" },
  { value: "Chorwacja", code: "hr" },
  { value: "Czechy", code: "cz" },
  { value: "Dania", code: "dk" },
  { value: "Francja", code: "fr" },
  { value: "Gruzja", code: "ge" },
  { value: "Hiszpania", code: "es" },
  { value: "Holandia", code: "nl" },
  { value: "Niemcy", code: "de" },
  { value: "Polska", code: "pl" },
  { value: "Portugalia", code: "pt" },
  { value: "Rumunia", code: "ro" },
  { value: "Serbia", code: "rs" },
  { value: "Słowacja", code: "sk" },
  { value: "Słowenia", code: "si" },
  { value: "Szkocja", code: "GB-SCT" },
  { value: "Szwajcaria", code: "ch" },
  { value: "Turcja", code: "tr" },
  { value: "Ukraina", code: "ua" },
  { value: "Węgry", code: "hu" },
  { value: "Włochy", code: "it" },
];
