export const TeamList = [
  { value: "Algieria", code: "dz" },
  { value: "Anglia", code: "GB-ENG" },
  { value: "Arabia Saudyjska", code: "sa" },
  { value: "Argentyna", code: "ar" },
  { value: "Australia", code: "au" },
  { value: "Austria", code: "at" },
  { value: "Belgia", code: "be" },
  { value: "Bośnia i Hercegowina", code: "ba" },
  { value: "Brazylia", code: "br" },
  { value: "Chorwacja", code: "hr" },
  { value: "Curaçao", code: "cw" },
  { value: "Czechy", code: "cz" },
  { value: "DR Konga", code: "cd" },
  { value: "Ekwador", code: "ec" },
  { value: "Egipt", code: "eg" },
  { value: "Francja", code: "fr" },
  { value: "Ghana", code: "gh" },
  { value: "Haiti", code: "ht" },
  { value: "Hiszpania", code: "es" },
  { value: "Holandia", code: "nl" },
  { value: "Irak", code: "iq" },
  { value: "Iran", code: "ir" },
  { value: "Japonia", code: "jp" },
  { value: "Jordania", code: "jo" },
  { value: "Kameroon", code: "cm" },
  { value: "Kanada", code: "ca" },
  { value: "Katar", code: "qa" },
  { value: "Kolumbia", code: "co" },
  { value: "Korea Południowa", code: "kr" },
  { value: "Maroko", code: "ma" },
  { value: "Meksyk", code: "mx" },
  { value: "Niemcy", code: "de" },
  { value: "Norwegia", code: "no" },
  { value: "Nowa Zelandia", code: "nz" },
  { value: "Panama", code: "pa" },
  { value: "Paragwaj", code: "py" },
  { value: "Polska", code: "pl" },
  { value: "Portugalia", code: "pt" },
  { value: "Południowa Afryka", code: "za" },
  { value: "Senegal", code: "sn" },
  { value: "Szkocja", code: "GB-SCT" },
  { value: "Szwajcaria", code: "ch" },
  { value: "Szwecja", code: "se" },
  { value: "Tunezja", code: "tn" },
  { value: "Turcja", code: "tr" },
  { value: "Urugwaj", code: "uy" },
  { value: "USA", code: "us" },
  { value: "Uzbekistan", code: "uz" },
  { value: "Wybrzeże Kości Słoniowej", code: "ci" }
];