import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    paddingTop: 52,
  },
  image: {
    flex: 1,
  },
  profile: {
    borderColor: "red",
    marginTop: 20,
    width: "88%",
    marginLeft: 4,
  },
  button: {
    position: "absolute",
    zIndex: 2,
    marginTop: 4,
    marginLeft: 8,
  },
  avatar: {
    width: 60,
    height: 60,
    borderRadius: 60,
    marginTop: 2,
  },
  top: {
    width: "100%",
    height: 44,
    backgroundColor: "#003279",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    borderRadius: 20,
    paddingLeft: 10,
    paddingRight: 10,
    zIndex: -1,
  },
  space: {
    width: "24%",
  },
  nick: {
    color: "#FFFFFF",
    fontSize: 18,
    width: "42%",
  },
  viewPoints: {
    flexDirection: "row",
  },
  points: {
    color: "#FFFFFF",
    fontSize: 18,
    fontWeight: "bold",
    marginLeft: 12,
    marginRight: 2,
  },
  bottom: {
    width: "100%",
    height: 44,
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "flex-end",
    marginTop: -16,
    borderBottomLeftRadius: 16,
    borderBottomRightRadius: 16,
    zIndex: -2,
  },
  viewBottom: {
    backgroundColor: "#003279",
    flexDirection: "row",
    borderRadius: 10,
    marginBottom: 3,
    paddingLeft: 12,
    paddingRight: 12,
    padding: 2,
  },
  icon: {
    color: "#FFFFFF",
    fontSize: 18,
    marginRight: 10,
  },
  desc: {
    fontSize: 14,
    color: "#FFFFFF",
  },
  position: {
    zIndex: 2,
    position: "absolute",
    right: 12,
    bottom: 2,
    fontSize: 16,
    color: "#003279",
  },
  type1: {
    color: "#FFFFFF",
    width: 180,
    fontSize: 14,
    fontWeight: "bold",
    marginLeft: 4,
  },
  type2: {
    color: "#003279",
    width: 180,
    fontSize: 14,
    fontWeight: "bold",
    marginBottom: -6,
  },
  bottomKing: {
    width: "100%",
    height: 44,
    backgroundColor: "#FFFFFF",
    alignItems: "flex-end",
    justifyContent: "space-between",
    marginTop: -16,
    borderBottomLeftRadius: 16,
    borderBottomRightRadius: 16,
    paddingLeft: 10,
    paddingRight: 10,
    flexDirection: "row",
    zIndex: -2,
  },
  champion: {
    flexDirection: "row",
    alignItems: "center",
    width: 180,
  },
  info1: {
    width: 100,
    color: "#FFFFFF",
    fontSize: 14,
  },
  info2: {
    width: 100,
    color: "#003279",
    fontSize: 14,
    marginBottom: 4,
  },
  icon1: { fontSize: 22, color: "#FFFFFF" },
  icon2: {
    fontSize: 22,
    color: "#003279",
    marginBottom: 4,
  },
  flatlist: {
    bottom: "8%",
    width: "89%",
    marginLeft: 4,
    position: "absolute",
    height: "69%",
  },
  bottomSheet: {
    flex: 1,
    justifyContent: "center",
    marginTop: 4,
  },
  contentContainer: {
    flex: 1,
    alignItems: "center",
    height: "auto",
    flexWrap: "wrap",
    flexDirection: "row",
    justifyContent: "center",
    padding: 4,
  },
  viewTitle: {
    width: "100%",
    justifyContent: "center",
    alignItems: "center",
  },
  title: {
    color: "#003279",
    fontSize: 16,
  },
  team: {
    width: "30%",
    backgroundColor: "#003279",
    height: 30,
    borderRadius: 30,
    justifyContent: "center",
    alignItems: "center",
    margin: 4,
  },
  teamText: {
    color: "#FFFFFF",
  },
  viewModal: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0,0,0,0.67)",
  },
  viewModal2: {
    backgroundColor: "#003279",
    width: "85%",
    height: "74%",
    borderRadius: 12,
    padding: 16,
  },
  textModal: {
    color: "#fff",
    fontSize: 18,
    fontWeight: "bold",
    marginBottom: 12,
    textAlign: "center",
  },
  country: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: "#334155",
  },
  countryFlag: {
    borderRadius: 4,
    marginRight: 18,
  },
  countryText: {
    color: "#fff",
    fontSize: 16,
  },
  close: {
    backgroundColor: "#ed1c24",
    padding: 10,
    borderRadius: 6,
    marginTop: 12,
    alignItems: "center",
  },
  closeText: {
    color: "#fff",
    fontWeight: "bold",
  },
});

export default styles;
